// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/adapter/broker/rabbitmq"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/adapter/repository/postgres"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/adapter/transport/rest"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/adapter/transport/rest/handler"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/domain"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/scheduler"
	"github.com/ReilEgor/SiteSentinel/monitor-service/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(dsn string, rabbitURL rabbitmq.RabbitURL, resultsQueue rabbitmq.ConsumerQueueName, taskQueue rabbitmq.PublisherQueueName) (*App, func(), error) {
	db, cleanup, err := postgres.NewPostgresDB(dsn)
	if err != nil {
		return nil, nil, err
	}
	monitorRepository := postgres.NewMonitorRepository(db)
	connection, cleanup2, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	channel, cleanup3, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, taskQueue)
	monitorInteractor := usecase.NewMonitorInteractor(monitorRepository, publisher)
	siteScheduler := scheduler.NewSiteScheduler(monitorRepository, publisher)
	consumer := rabbitmq.NewConsumer(channel, resultsQueue, monitorInteractor)
	ginServer := rest.NewGinServer(monitorInteractor)
	app := &App{
		Logic:     monitorInteractor,
		Scheduler: siteScheduler,
		Consumer:  consumer,
		Server:    ginServer,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var SchedulerSet = wire.NewSet(scheduler.NewSiteScheduler)

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, rabbitmq.NewConsumer, wire.Bind(new(domain.TaskPublisher), new(*rabbitmq.Publisher)))

var RepositorySet = wire.NewSet(postgres.NewPostgresDB, postgres.NewMonitorRepository, wire.Bind(new(domain.MonitorRepository), new(*postgres.MonitorRepository)))

var UsecaseSet = wire.NewSet(usecase.NewMonitorInteractor, wire.Bind(new(domain.SiteUsecase), new(*usecase.MonitorInteractor)))

var HTTPSet = wire.NewSet(rest.NewGinServer, handler.NewHandler)

type App struct {
	Logic     domain.SiteUsecase
	Scheduler *scheduler.SiteScheduler
	Consumer  *rabbitmq.Consumer
	Server    *rest.GinServer
}
