// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/SiteSentinel/checker-service/internal/adapter/broker/rabbitmq"
	"github.com/ReilEgor/SiteSentinel/checker-service/internal/adapter/http_client"
	"github.com/ReilEgor/SiteSentinel/checker-service/internal/domain"
	"github.com/ReilEgor/SiteSentinel/checker-service/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, resultsQueue rabbitmq.ConsumerQueueName, taskQueue rabbitmq.PublisherQueueName) (*App, func(), error) {
	httpChecker := http_client.NewHTTPChecker()
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, taskQueue)
	checkerInteractor := usecase.NewCheckerUsecase(httpChecker, publisher)
	consumer := rabbitmq.NewConsumer(channel, resultsQueue, checkerInteractor, publisher)
	app := &App{
		Logic:    checkerInteractor,
		Consumer: consumer,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var HTTPSet = wire.NewSet(http_client.NewHTTPChecker, wire.Bind(new(domain.Checker), new(*http_client.HTTPChecker)))

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, rabbitmq.NewConsumer, wire.Bind(new(domain.ResultPublisher), new(*rabbitmq.Publisher)))

var UsecaseSet = wire.NewSet(usecase.NewCheckerUsecase, wire.Bind(new(domain.CheckerUsecase), new(*usecase.CheckerInteractor)))

type App struct {
	Logic    domain.CheckerUsecase
	Consumer *rabbitmq.Consumer
}
