// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ReilEgor/SiteSentinel/pkg/models"
)

// CheckerUsecase is an autogenerated mock type for the CheckerUsecase type
type CheckerUsecase struct {
	mock.Mock
}

// ExecuteCheck provides a mock function with given fields: ctx, site
func (_m *CheckerUsecase) ExecuteCheck(ctx context.Context, site models.Site) (models.CheckResult, error) {
	ret := _m.Called(ctx, site)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCheck")
	}

	var r0 models.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Site) (models.CheckResult, error)); ok {
		return rf(ctx, site)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Site) models.CheckResult); ok {
		r0 = rf(ctx, site)
	} else {
		r0 = ret.Get(0).(models.CheckResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Site) error); ok {
		r1 = rf(ctx, site)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCheckerUsecase creates a new instance of CheckerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckerUsecase {
	mock := &CheckerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
