// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, url
func (_m *Checker) Check(ctx context.Context, url string) (bool, int, time.Duration, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 int
	var r2 time.Duration
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, int, time.Duration, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) time.Duration); ok {
		r2 = rf(ctx, url)
	} else {
		r2 = ret.Get(2).(time.Duration)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, url)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
