// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ReilEgor/SiteSentinel/pkg/models"

	uuid "github.com/google/uuid"
)

// MonitorRepository is an autogenerated mock type for the MonitorRepository type
type MonitorRepository struct {
	mock.Mock
}

// AddSite provides a mock function with given fields: ctx, userID, url, interval
func (_m *MonitorRepository) AddSite(ctx context.Context, userID uuid.UUID, url string, interval int) (*models.Site, error) {
	ret := _m.Called(ctx, userID, url, interval)

	if len(ret) == 0 {
		panic("no return value specified for AddSite")
	}

	var r0 *models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) (*models.Site, error)); ok {
		return rf(ctx, userID, url, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) *models.Site); ok {
		r0 = rf(ctx, userID, url, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, userID, url, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSitesToSchedule provides a mock function with given fields: ctx
func (_m *MonitorRepository) GetSitesToSchedule(ctx context.Context) ([]models.Site, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSitesToSchedule")
	}

	var r0 []models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Site, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Site); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSites provides a mock function with given fields: ctx, userID
func (_m *MonitorRepository) GetUserSites(ctx context.Context, userID uuid.UUID) ([]*models.Site, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSites")
	}

	var r0 []*models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Site, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Site); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveCheckResult provides a mock function with given fields: ctx, res
func (_m *MonitorRepository) SaveCheckResult(ctx context.Context, res models.CheckResult) error {
	ret := _m.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CheckResult) error); ok {
		r0 = rf(ctx, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSiteStatus provides a mock function with given fields: ctx, siteID, isUp
func (_m *MonitorRepository) UpdateSiteStatus(ctx context.Context, siteID uuid.UUID, isUp bool) error {
	ret := _m.Called(ctx, siteID, isUp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSiteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, siteID, isUp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMonitorRepository creates a new instance of MonitorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitorRepository {
	mock := &MonitorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
