// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ReilEgor/SiteSentinel/pkg/models"

	uuid "github.com/google/uuid"
)

// SiteUsecase is an autogenerated mock type for the SiteUsecase type
type SiteUsecase struct {
	mock.Mock
}

// AddSite provides a mock function with given fields: ctx, userID, url, interval
func (_m *SiteUsecase) AddSite(ctx context.Context, userID uuid.UUID, url string, interval int) (*models.Site, error) {
	ret := _m.Called(ctx, userID, url, interval)

	if len(ret) == 0 {
		panic("no return value specified for AddSite")
	}

	var r0 *models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) (*models.Site, error)); ok {
		return rf(ctx, userID, url, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) *models.Site); ok {
		r0 = rf(ctx, userID, url, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, userID, url, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSite provides a mock function with given fields: ctx, userID, url
func (_m *SiteUsecase) DeleteSite(ctx context.Context, userID uuid.UUID, url string) (*models.Site, error) {
	ret := _m.Called(ctx, userID, url)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSite")
	}

	var r0 *models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.Site, error)); ok {
		return rf(ctx, userID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.Site); ok {
		r0 = rf(ctx, userID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSites provides a mock function with given fields: ctx, userID
func (_m *SiteUsecase) GetUserSites(ctx context.Context, userID uuid.UUID) ([]*models.Site, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSites")
	}

	var r0 []*models.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Site, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Site); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessCheckResult provides a mock function with given fields: ctx, result
func (_m *SiteUsecase) ProcessCheckResult(ctx context.Context, result models.CheckResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for ProcessCheckResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CheckResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSiteUsecase creates a new instance of SiteUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteUsecase {
	mock := &SiteUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
