// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ReilEgor/SiteSentinel/pkg/models"
)

// TaskPublisher is an autogenerated mock type for the TaskPublisher type
type TaskPublisher struct {
	mock.Mock
}

// PublishCheckTask provides a mock function with given fields: ctx, site
func (_m *TaskPublisher) PublishCheckTask(ctx context.Context, site models.Site) error {
	ret := _m.Called(ctx, site)

	if len(ret) == 0 {
		panic("no return value specified for PublishCheckTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Site) error); ok {
		r0 = rf(ctx, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskPublisher creates a new instance of TaskPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskPublisher {
	mock := &TaskPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
